<?php
session_start();
require "validate.php";
require "server.php";
require "../jpgraph/jpgraph.php";
require "../jpgraph/jpgraph_bar.php";
require "../fpdf/fpdf.php";

if (!isset($_SESSION['loggedin'])) {
    header('Location:../HTML/index.html');
    exit();
}

$stmt = $con->prepare("SELECT COUNT(*) FROM request WHERE `date` BETWEEN (CURDATE() - INTERVAL 1 MONTH) AND CURDATE()");
$stmt->execute();
$stmt->bind_result($countLastMonth);
$stmt->fetch();
$stmt->close();

$stmt = $con->prepare("SELECT productName FROM (SELECT COUNT(*) AS freq, product.productName FROM product JOIN requestedproduct ON product.productCode = requestedproduct.productCode JOIN request ON requestedproduct.requestID = request.requestID WHERE request.date BETWEEN (CURDATE() - INTERVAL 1 MONTH) AND CURDATE() GROUP BY requestedproduct.productCode ORDER BY freq DESC LIMIT 1) AS q1");
$stmt->execute();
$stmt->bind_result($mostRequestedProduct);
$stmt->fetch();
$stmt->close();

$stmt = "SELECT freq FROM (SELECT COUNT(*) AS freq, staffID FROM request WHERE request.`date` BETWEEN(CURDATE() - INTERVAL 1 MONTH) AND CURDATE() GROUP BY staffID ORDER BY freq DESC) AS q1";
$result = $con->query($stmt);

$staffOrdAmount = array();

while ($row = $result->fetch_assoc()){
    array_push($staffOrdAmount, $row['freq']);
}

$stmt = "SELECT staffID FROM (SELECT COUNT(*) AS freq, staffID FROM request WHERE request.`date` BETWEEN(CURDATE() - INTERVAL 1 MONTH) AND CURDATE() GROUP BY staffID ORDER BY freq DESC) AS q1";
$result = $con->query($stmt);

$staffOrdID = array();

while ($row = $result->fetch_assoc()) {
    array_push($staffOrdID, $row['staffID']);
}

$graph = new Graph(300, 200, "auto");
$graph->SetScale('textlin');
$graph->xaxis->SetTickLabels($staffOrdID);
$graph->SetShadow();
$graph->SetMargin(40, 30, 20, 40);
$graph->title->Set("Requests per Staff Member");
$graph->title->SetFont(FF_FONT1, FS_BOLD);
$bplot = new BarPlot($staffOrdAmount);

$graph->Add($bplot);
$graph->Stroke("./staffreq.png");

$pdf = new FPDF();
$pdf->SetTitle("G4U Monthly Report");
$pdf->AddPage();
$pdf->SetFont("Arial", "B", 16);
$pdf->Image("../images/logo_sm.png");
$pdf->Cell(0, 10, 'Gadgets4U Monthly Report. Generated by: ' . $_SESSION['name'] . " on " . date("d/m/Y"), 0, 1, "C");
$pdf->SetFont("Arial", "", 16);
$pdf->Ln();
$pdf->Cell(40, 10, "Amount of Requests in Last Month: " . $countLastMonth);
$pdf->Ln();
$pdf->Cell(0,10, 'Most Requested Product: ' . $mostRequestedProduct);
$pdf->Ln();
$pdf->Image("staffreq.png");
$pdf->Output();
